### ISSUE TITLE
Cannot read properties of undefined (reading 'includes) on build with depedencies

### ISSUE THREAD

**Issue by UZApocalyps** [Cobwebsite/Aventus#2]
Hi,
I'm trying to make a package, that contains a class. 
![image](https://github.com/Cobwebsite/Aventus/assets/62464003/6a3822fd-b047-4297-a590-8cffd12ab894)

Then I try to import it in another project using "dependencies" array in configuration file
![image](https://github.com/Cobwebsite/Aventus/assets/62464003/2978432e-f70b-4edb-a947-33a9466b3ac9)

The problem is when Aventus try to build it throw an "Cannot read properties of undefined (reading: 'includes')". Maybe it's my package that is not properly implemented. If it's my package can you add to documentation how to build a package.

Thanks

**Comment by max529** [comment]
You shouldn't create a package file manually. A package file is the compiled version of one build. You can find more informations about how to import package [here](https://aventusjs.com/docs/config/lib) and how to export package via config file [here](https://aventusjs.com/docs/config/build) under **outputPackage**
