### ISSUE TITLE
How import typescript types into aventus (Chart.js 4.3.0)

### ISSUE THREAD

**Issue by SuperQuentin** [Cobwebsite/Aventus#4]
Hi,

I needed to include type of chart.js and the way i found was to build the lib locally and use dts-bundle-generator to generate me a chart.def.avt file.

`dts-bundle-generator -o chart.def.avt .\dist\types.d.ts --no-check`

i just wrap a declare global {} scope around the generated content and it's seems to be working fine. 

I would like to know if in the future there will be an official tool/way to include that typescript declaration files

**Comment by max529** [comment]
It is not planned to be able to directly include a typescript definition file

However, it is possible to use npm packages that are written in typescript to include it directly in the final build.

I've created an example to illustrate how to do this. Make sure you are running version 1.0.101 of Aventus (I had to correct some issues).

Example for chart js : [Aventus sample](https://github.com/Cobwebsite/Aventus-Sample/tree/master/chartjs)
